### ISSUE TITLE
slack.name empty

### ISSUE THREAD

**Issue by mbsimonovic** [drone-plugins/drone-slack-blame#30]
![screen shot 2018-10-02 at 09 45 36](https://user-images.githubusercontent.com/888008/46335499-fa4a5600-c627-11e8-891a-925f7487fa2b.png)

This happens for both github and gitlab repos. 

.drone.yml is copy/pasted from the docs:
```yaml
  slack_blame:
    image: plugins/slack-blame
    secrets: [ slack_token ]
    channel: paxdb-build-bot
    success_template: |
       build is green :) Thanks @{{slack.name}}
    failure_template: |
       build is broken :( Blame {{slack.name}}
    when:
        status: [ failure, success ]
```

For the gitlab build the emails for gitlab and slack are identical, but for github they are different, so that shouldn't be a reason? 

drone runs in docker containers:

- drone/agent sha256:972f5ed363b0dbff8f13b79d787570a3cd5c35cd2d294ab2c4ec0c779d4e074e
- plugins/slack-blame sha256:7cc14b048edddd4b4b68a026750e4d8c48678af9aaded55addb559d48c5e9bb8

**Comment by donny-dont** [comment]
The logs inside the build itself should give an idea on what is going on. The drone agent logs don't really say anything. The plugin itself shows a bunch of information on what its up to. I would need to know if the user was even found.

**Comment by mbsimonovic** [comment]
how can i debug the plugin? there's probably a way to manually run it as a docker container?

**Comment by tboerger** [comment]
Just execute `docker run -ti --rm plugins/slack-blame -h` and you will see the available options for manual execution.

**Comment by mbsimonovic** [comment]
INFO[0000] Successfully authenticated with Slack API     team="apples inc" user=milan
INFO[0000] Searching for user by email                   email=
INFO[0000] Icon is an emoji
ERRO[0000] Could not find author                         author=

**Comment by mbsimonovic** [comment]
the plugin doesn't report any errors when run as: `--token **** --success_template '{{slack}}  @{{slack.name}}'   --commit.author.email *********@gmail.com`:

```
INFO[0000] Successfully authenticated with Slack API     team="apples inc" user=milan
INFO[0000] Searching for user by email                   email=**********@gmail.com
INFO[0000] Found user                                    email=**********@gmail.com username=milan
INFO[0000] Icon is an emoji
INFO[0000] Notified user                                 username=milan
INFO[0000] Channel notified                              channel="#drone-bot"
```

but the message is still missing usernames.

**Comment by donny-dont** [comment]
It might be ‘slack.username’

**Comment by mbsimonovic** [comment]
tried it all, slack.Username, slack.username, slack.name, just username, ... nothing works

**Comment by bradrydzewski** [comment]
I think it is `user.name`

**Comment by tboerger** [comment]
Since the struct only got a user attribute it must be user.name or user.username.

**Comment by mbsimonovic** [comment]
> I think it is `user.name`

bingo! so update the docs and close the issue. thanks guys

**Comment by srijeet0406** [comment]
@mbsimonovic Did the `user.name` thing actually work for you? I cant get it working, here's my pipeline:
`
  notify:
    image: plugins/slack-blame
    token: <my token here>
    channel: <name of my channel here>
    success_template: |
      The build is fixed! Thanks @{{user.name}}
    failure_template: |
      The build is broken! Blame @{{user.name}}
`

Here's my output:
`
Build succeeded
The build is fixed! Thanks @
`

Any help appreciated :)

**Comment by mbsimonovic** [comment]
yeah, works fine with {{user.name}}

```
  slack_notify:
    image: plugins/slack-blame
    secrets: [ slack_token ]
    channel: drone-bot
    success_template: |
      API build is green :) Thanks {{user.name}}
    failure_template: |
      API build is broken :( Blame {{user.name}}
    when:
      status:  [ failure, success ]
```
you should debug, perhaps you have to map if the commit email doesn't match the account email
