### ISSUE TITLE
Always sends success

### ISSUE THREAD

**Issue by zatkowich** [drone-plugins/drone-slack-blame#46]
I have the following step

```
- name: Notify author of result
  image: plugins/slack-blame
  settings:
    failure_template: "failure"
    mapping: /drone/src/ci/common/drone/slack-github-user-mapping.json
    success_template: "success"
    token: xxx
  when:
    status:
    - failure
  depends_on:
  - Parse Slack usernames
  - Check code formatting
  - Run SonarQube scanner
```

When one of steps in depends_on fails Slack plugin detects failure in when and runs - that is correct.
However the status sent into message is wrong - success - see the message in Slack:

**Build succeeded
success**
